---
title: "MS2 library: import spectras"
author: "Mar Garcia-Aloy"
output: 
  BiocStyle::html_document:
    toc: false
    number_sections: false
    toc_float: false
---

```{r startpoint, include = FALSE}
startpoint <- Sys.time()
knitr::opts_chunk$set(echo = TRUE, warning = TRUE, message = TRUE)
```

```{r}
library(readxl)
library(Spectra)
library(Rdisop)
library(CompoundDb)

ions <- c("[M-H]-", "[M+H]+")
names(ions) <- c("NEG", "POS")

cmps <- read_xlsx("C:/Users/garciaalom/Google Drive/laboratory/db_compounds.xlsx")
inj <- read_xlsx("C:/Users/garciaalom/Google Drive/laboratory/standards_injections.xlsx")
inj <- inj[!is.na(inj$ID_cmp),]

for(k in seq(length(ions))){
  i.pol <- names(ions)[k]
  
  i.inj <- inj[inj$polarity == i.pol, ]
  
  for(i in seq(nrow(i.inj))){
    i.cmp <- unlist(strsplit(i.inj$ID_cmp[i], "; "))
    for(j in seq(length(i.cmp))){
      i.fml <- cmps$formula[cmps$ID_cmp == i.cmp[j]]
      if(is.na(i.fml)){
        print(paste("Search FORMULA of", cmps$compound[cmps$ID_cmp == i.cmp[j]],
                    "-", i.cmp[j]))
      } else {
        i.fl <- Spectra(paste0("C:/Users/garciaalom/Documents/GitHub/MS2_library/mzML/",
                               i.inj$path[i], i.inj$filename[i], ".mzML"), 
                        backend = MsBackendDataFrame()#MsBackendMzR()
        )
        i.fl <- i.fl[msLevel(i.fl) > 1]
        i.mz <- unlist(mass2mz(getMolecule(i.fml)$exactmass, ions[k]))
        i.fl <- filterPrecursorMz(i.fl, i.mz + 0.01 * c(-1, 1))
        i.chr <- i.inj$chromatography[i]
        i.rt <- unlist(c(cmps[cmps$ID_cmp == i.cmp[j], 
                              c(paste0(i.chr, "_min"), paste0(i.chr, "_max"))]))
        if(is.na(i.rt)[1]){
          print(paste("Check RT of", cmps$compound[cmps$ID_cmp == i.cmp[j]], 
                      "in", i.chr))
        } else {
          i.fl <- filterRt(i.fl, i.rt + (30 * c(-1, 1)))
        } # end if(is.na(i.rt)) 
        if(length(i.fl) > 0){
          i.fl$name <- i.cmp[j]
          if(exists("sps.ms2")){
            sps.ms2 <- c(sps.ms2, i.fl)
          } else{
            sps.ms2 <- i.fl
          } # end if(exists("sps.ms2")
        } # end length(i.fl)
      } # end if(is.na(i.fml))
    } # end i.cmp "j"
  } # end i.fl "i"
  
  save(sps.ms2, file = paste0("MS2library_", i.pol, ".RData"))
  rm(sps.ms2)
}
```


# Session information

```{r session}
Sys.time()-startpoint
devtools::session_info()
```